### ISSUE TITLE
Unexpected token error when running axe-storybook as part of CI

### ISSUE THREAD

**Issue by NicholasVermaak** [chanzuckerberg/axe-storybook-testing#43]
I am getting the below error when running axe-storybook as part of CI. The same command works fine locally. Below is a screenshot showing the command we ran and the error:

Anyone seen something similar before? any advice would be appreciated.

![image](https://user-images.githubusercontent.com/89131420/137844616-5cf6706c-4ef8-49cb-977b-01c0868e5b48.png)

**Comment by NicholasVermaak** [comment]
Thanks for the prompt reply @ahuth, I'm currently running node v14.17.6 and then 4.1.1 for axe-storybook-testing.

**Comment by ahuth** [comment]
Thanks, @NicholasVermaak!

Node 14 should definitely support that syntax, and I don't see any optional chaining in Zod's compiled output. Not sure what's going on here.

I've published v4.1.2 of axe-storybook testing. Can you try it out?

I don't really have a reason to think it'll solve this, but it does upgrade Zod and uses a different compilation process (esbuild instead of babel). So maybe the packaged code will be different enough that it gets resolved. And if not, I'll dig in some more.

**Comment by ahuth** [comment]
v5.0.0 is published, which may also resolve this.

I'm going to close this issue for now. Let me know if it's still a problem, and I'll be happy to investigate some more.
