### ISSUE TITLE
Script always fails with error "Storybook object not found on window. Open your storybook and check the console for errors."

### ISSUE THREAD

**Issue by karrui** [chanzuckerberg/axe-storybook-testing#44]
When running my CLI command (regardless of config), the cli always hangs with the following output:

```
$ npm run test:a11y -- --headless false --browser firefox

> form-frontend@0.1.0 test:a11y /Users/karrui/Projects/FormSG/frontend
> axe-storybook "--headless" "false" "--browser" "firefox"

[firefox] accessibility
Error! The suite failed to run
An error was encountered before we started testing stories. Likely this means the browser failed to open.

Error: Storybook object not found on window. Open your storybook and check the console for errors.

0 passing (0ms)
1 failing
0 pending
```

**Comment by ahuth** [comment]
Alright, fix coming in #45. Will let you know when it's published, and thanks for reporting the issue!

What's happening is:
- The `axe-storybook` is a node command that uses Playwright to get some information from a browser pointed at the static Storybook build.
- Getting that information out of the browser requires it to be JSON serializable.
- Some addon parameters (such as MSW's) aren't JSON serializable, causing `undefined` to be returned.

We can avoid that by only retrieving the information we know we need, instead of trying to get everything out of the browser.

**Comment by ahuth** [comment]
4.1.3 is released with the fix. @karrui when you get a chance, can you verify that it solves the issue for you? (It does in my testing on the repo)

**Comment by karrui** [comment]
Awesome, it works now. Once again, thanks for such a quick response!
